### ISSUE TITLE
Paragraphs in Markdown sources

### ISSUE THREAD

**Issue by programandala-net** [barumau/pandunia#31]
The paragraphs of the Markdown sources have no line break. (I've seen the Spanish, English and Esperanto versions). They have only one single long line of text.

The problem is editing and comparing versions that way is much more difficult.

Is it ok, in order to update the sources, if I edit them with text lines of say 70 chars?

**Comment by Darellur** [comment]
What kind of a line break are you talking about? Would it not affect readablity? I believe paragraphs are already sufficiently short.

**Comment by programandala-net** [comment]
En/Je/On 2018-12-10 12:39, Jan Kalwasiński escribió / skribis / wrote :

> What kind of a line break are you talking about? Would it not affect
> readablity? I believe paragraphs are already sufficiently short.

I'm talking about the layout of the paragraphs in the Markdown sources.
It has nothing to do with the look of the final HTML, which will not be
affected.

As I said, the problem is every paragraph in the sources is one single
line of text.  E.g., the first paragraph of esperanto/kanun.md ("Frazoj
en naturaj lingvoj ... precizigas.") is one single line with 459
characters!

That's a big problem for editing the source and making diffs with the
usual coding tools.

-- 
Marcos Cruz
http://programandala.net

**Comment by Darellur** [comment]
I haven't noticed that functionality; I support that

**Comment by barumau** [comment]
salam! The reason for this formatting is that we originally used MdWiki, which added line break for every newline. (Later I found the configuration parameter to fix that.)

Long lines really disturbs comparison of different language versions. I support this initiative to break the lines at about 70 characters. However I reserve the right to write sometimes longer lines up 100 characters when it seems more appropriate. (Some sentences are longer in certain languages.)

**Comment by programandala-net** [comment]
En/Je/On 2018-12-14 06:12, barumau escribió / skribis / wrote :

> Long lines really disturbs comparison of different language versions.
> I support this initiative to break the lines at about 70 characters.

Great. I will start updating the Spanish and Esperanto pages that way.
The task will be very much easier.

> However I reserve the right to write sometimes longer lines up 100
> characters when it seems more appropriate. (Some sentences are longer
> in certain languages.)

But you can insert line breaks into Markdown paragraphs or list items
and the final HTML will be exactly the same.

The only limitation I see is tables. Markdown tables are rigid and
limited, compared to Asciidoctor tables. In Markdown, table rows or
cells can not be splitted into several lines of texts, so sometimes you
are forced to write too long lines of source text.

-- 
Marcos Cruz
http://programandala.net

**Comment by programandala-net** [comment]
By the way, there's an exception: Markdown headings can not be splitted into several lines of text. Long titles must be preserved in one single line of text.
