### ISSUE TITLE
Proposal for representing languages in the homepage

### ISSUE THREAD

**Issue by programandala-net** [barumau/pandunia#33]
Flags are intended **to represent languages in the homepage**, but, except the Esperanto and Pandunia flags, they actually represent countries.

New translations will be added in the future, and new flags will be added as well representing more countries, regions of countries or even states of federations or confederations, or whatever...  but certainly not languages (except, as said, flags and symbols of constructed languages).

**I propose a more neutral approach**: Preserve the sentences currently used as link texts, but highlighting the name of the languages with the proper markup, e.g. bold.  Then replace the national flags with the ISO 639-2 language codes in brackets, which will be also the alphabetical sorting key of the list (another sign of neutrality). Besides, since all ISO 639-2 codes are three letters long, the list will look nicer because all entries will be left justified (now three entries have two national flags at the left instead of one).

For a **more detailed explanation and arguments** about the issue of flags and languages, please read a short article I found years ago, by Jukka Korpela (please ignore the apparent rudeness of the page heading): [Why you should not use a flag as a symbol of language](http://jkorpela.fi/flags.html).

I think this little but significant change in the interface is **consistent with Pandunia's spirit of neutrality**, by restricting the main menu to a pure language selection. Beside, it will make things much easier in the future, when the number of translations will grow.

What do you think?

**Comment by programandala-net** [comment]
En/Je/On 2018-12-17 16:29, barumau escribió / skribis / wrote :

> The flags are there for better looks and for faster scanning by the
> eyes.

Of course, I understand your point. Icons are easier to find at first
sight, provided there are not too many of them.

But things will get more complicated as new translations will be added
in the future, because the main problem remains: association between
flags and languages.  See more examples and data:

http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/

Even a recommended practice by W3C:

https://www.w3.org/International/questions/qa-link-lang#flags

> ISO language codes are worse for visual scanning and many people don’t
> even know them.

Right. The name of the language, in its local format, is the important
thing:

http://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/

I know this is not a big problem at the moment, but anyway I'll draft
several example alternatives, and we'll see the look and usability.

-- 
Marcos Cruz
http://programandala.net

**Comment by barumau** [comment]
I changed the layout and added more flags next to each language link. Is it better now?

See https://github.com/barumau/pandunia/commit/7071252620415e3fa7da0428a3c962e4e4408e90

A new idea: let's add language links to the navigation bar. There we shall use the name of the language in its local format, because your instructions are applicable there. The front page is a different matter.

**Comment by programandala-net** [comment]
En/Je/On 2018-12-21 00:48, Risto Kupsala escribió / skribis / wrote :

> I changed the layout and added more flags next to each language link.
> Is it better now?

I can't not see the Unicode regional indicator symbols at the moment on
Debian, with any of the many browsers installed. I think I need to
update something :)

But I've seen the actual codes in the Markdown source, and also their
aspect in https://www.unicode.org/charts/PDF/U1F100.pdf.

Replacing national/country/regional flags with standard regional codes
seems more neutral, provided the codes are not a simple replacement of
flags, but they just show the regions where the languages are spoken, at
least the most important zones, and provided there are standard codes
for all needed regions.

But anyway part of the underlying problem remains:  Association of
languages with non-linguistic entities (countries, regions...).  For
example, how many flags/regional symbols are enough (and in which order)
in order to make finding every language "easier" for "most" speakers,
without creating problems for "many" others?

Beside, the association with regions creates an exception for conlangs'
flags and symbols.

On the long term, problems will grow (eventually, changes, updates,
addings or removals of flags or region codes will be required (or even
demanded), unless only a single, objective, linguistic-only, list of
languages is displayed, optionally with an accompanying text in the
language itself, like the texts that are already displayed, which are
useful in order to explain the target of the link (they could be the
link titles as well, or instead).

I think finding the name of my language, written in my language, in an
alphabetically ordered list of 10 or 20 languages, where language names
are the only links and clearly visible, is not a problem, even for a
first-time visitor.  Even if the list had 100 languages you could find
the desired one with just 3 o 4 keystrokes or mouse clicks.  Or better
you can simply search the page for the language name by activating your
browser's text search function with a single keystroke or a couple of
clicks.

> A new idea: let's add language links to the navigation bar. There we
> shall use the name of the language in its local format, because your
> instructions are applicable there. The front page is a different
> matter.

Making moving from one language version to another easier seems a good
idea, yes!

Note the local format must include also capitalization. E.g. "español"
and "français" must be lowercase, like "pandunia". I don't know about
Indonesia, Polski, Português, Русский and Suomi.
 
-- 
Marcos Cruz
http://programandala.net

**Comment by Darellur** [comment]
_polski_ is lowercase in Polish

**Comment by barumau** [comment]
That is exactly the reason why there are no capital letters in Pandunia. What an annoyance! Anyway, I corrected them.

The front page is a mixture of many scripts and I believe that graphical symbols like the flags make it easier to navigate and more pleasant to look at. It will stay like that for now.

Maybe in the future we will have to change it for 30, 50 or 100 translations, but that moment isn't now.

**Comment by barumau** [comment]
On the second thought, it can be simplified a little. ;)

I made the text larger and the texts shorter. Is it OK now? https://github.com/barumau/pandunia/commit/d2dcbb84ddd93496fc7e9f9f1feb38576e9a8492

**Comment by programandala-net** [comment]
En/Je/On 2018-12-25 22:47, Risto Kupsala escribió / skribis / wrote :

> On the second thought, it can be simplified a little. ;)
> 
> I made the text larger and the texts shorter. Is it OK now? https://github.com/barumau/pandunia/commit/d2dcbb84ddd93496fc7e9f9f1feb38576e9a8492

Now it looks clearer, because the language names are easier to read.
Even further simplification is still possible: remove the prepositions,
and replace the lists of country codes with a single ISO language code
in parens :)

-- 
Marcos Cruz
http://programandala.net

**Comment by programandala-net** [comment]
En/Je/On 2018-12-25 22:35, Risto Kupsala escribió / skribis / wrote :

> That is exactly the reason why there are no capital letters in
> Pandunia. What an annoyance!

I agree. Capital letters make things harder in an auxlang, because a set
of conventional rules must be prescribed.

> Anyway, I corrected them.

Note also "Esperanto" must have a capital letter in Esperanto itself.

> The front page is a mixture of many scripts and I believe that
> graphical symbols like the flags make it easier to navigate and more
> pleasant to look at. It will stay like that for now.

On the contrary, I think the list, clearly ordered, with the language
names in their native format, is simpler and more elegant...  like
Pandunia ;)

Anyway, country codes are not less problematic than flags, because you
have to choose only a few of them and an order, and no choice is
perfect.  For example, I suppose you choosed "ES MX CO AR" for Spanish
because they are the top four countries in native speakers, and "ES" is
the first one because Spain is the origin of the language, though it
should be third one by its number of speakers...  The problem is
analogous at any regional level: for example, beside Castilian Spanish,
there are more languages spoken in Spain, even in more than one single
administrative region each, so "ES" could be used to identify the zones
of those languages as well, together with their regional codes...

Trying to link languages with countries or regions is not only
impossible, but also an endless headache, while using only language
names and/or language codes is simple.

For example, if someone from Argentina would want to adapt the Spanish
version of the Pandunia grammar to the Argentinian variant of the
Spanish language (which has a few differences in verb forms,
pronunciation and vocabulary),  the simplest solution would be to
duplicate the pages and the "español" menu entry, marking the difference
in a standard format, using the language ISO code and the regional
variant of the language:

- English (en)
- español (es-AR)
- español (es-ES)
- Esperanto (eo)
- français (fr)

Simple.

As for the current order:

Why Esperanto and Pandunia are at the end, instead of in their
alphabetical position?

Why Melayu/Indonesia is in its current position? Besides, in a future
longer list, maybe two separate entries, with identical link target,
would be clearer in that and other similar cases, where languages have
more than one common name.

-- 
Marcos Cruz
http://programandala.net
