### ISSUE TITLE
Depending on the pages, Pandunia does or doesn’t have the letter v

### ISSUE THREAD

**Issue by ariasuni** [barumau/pandunia#70]
In the [Frequently Asked Questions](http://www.pandunia.info/engli/eske_i_jawabe.html):

> In fact, the majority of letters (19 in total) are pronounced in general in the way in Pandunia and English, 5 are different, and two (q and v) are missing from Pandunia.

In [Pandunia - a global contact language](http://www.pandunia.info/engli/dunia_bax.html):

> Pandunia can be spelled regularly because it has fewer speech sounds (24) than there are letters in the basic Roman alphabet (26). The alphabet of Pandunia is:
a b c d e f g h i j k l m n o p r s t u w x y z

But in [Basics of Pandunia](http://www.pandunia.info/engli/baze.html) and [Spelling of Pandunia](http://www.pandunia.info/engli/abc.html), the v is listed among the letters.

The [Pandunia presentation](http://www.pandunia.info/engli/Pandunia-presentation.pdf) disagrees with itself on page 11:

> Alphabet: a b c d e f g h i j k l m n o p r s t u v w x y z
> […]
> Fricatives: f s z x h

**Comment by barumau** [comment]
I made corrections in https://github.com/barumau/pandunia/commit/c94a21ca45dbbba7baa5b3d232a4d58d424cfcab
